# Generated by Django 4.1.5 on 2023-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blogpart.tags'),
        ),
    ]
