# Generated by Django 4.1.5 on 2023-02-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpart', '0005_rename_name_tags_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
