# Generated by Django 4.1.7 on 2023-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(choices=[('NS', 'NODEJS'), ('DJ', 'Django'), ('FB', 'Facebook'), ('HU', 'Heroku'), ('IS', 'ISRO')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
