# Generated by Django 4.1.3 on 2023-02-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackflow', '0002_alter_question_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='stackflow.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
